openapi: 3.0.1
info:
  title: CustomMediator
  description: API Definition of CustomMediator
  version: 1.0.0
servers:
- url: http://localhost:8290/custom-mediator
paths:
  /:
    get:
      responses:
        default:
          description: Default response
