openapi: 3.0.1
info:
  title: TestDS
  description: API Definition of TestDS
  version: 1.0.0
servers:
- url: http://localhost:8290/ds
paths:
  /customer:
    get:
      responses:
        default:
          description: Default response
